[package]
name = "tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
reqwest = { version = "0.12.7", features = ["json"] }
serde_json = "1.0.128"
prettytable-rs = "0.10.0"
futures = "0.3.30"